# Generated by Django 3.2.13 on 2022-07-09 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=10000)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('usuario', models.CharField(max_length=250)),
                ('canal', models.CharField(max_length=250)),
            ],
        ),
    ]
