# Generated by Django 3.2.13 on 2022-07-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(blank=True, verbose_name='2022-07-12 10:02:01'),
        ),
    ]
