# Generated by Django 3.2.13 on 2022-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_mensaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(verbose_name='2022-07-12 10:07:27'),
        ),
    ]
